### Application
scout.application.name=FT Inventory Server
scout.application.version=${project.version}

### Service tunnel
scout.auth.publicKey=MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEg46teRsskAMVnhc21RKCx4e8FkSK/6IXrZ95nyYacqiD4O7ieMggS06QHYwi711Bk/Y3T7tyvAVwALYbgIR5pw==
