### Application
scout.application.name=Inventory Server
scout.application.version=development

### Environment
scout.devMode=true

### Service tunnel
scout.auth.publicKey=MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAENimj+a/zyllCDGZz7BWZL7HB6EjBVfFIchAPjO73yfBPKAbmZu5YRnKYC2ISa/8ZOqBb7TrDNsze3JoqxFfM/A==

inventory.database.jdbc.mappingName=jdbc:postgresql://qnap251:5432/ftdb
inventory.database.jdbc.username=ftdb
inventory.database.jdbc.password=ftdb

