<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>pers.mr.ft</groupId>
    <artifactId>inventory</artifactId>
    <version>1.12.0-SNAPSHOT</version>
    <relativePath>../inventory</relativePath>
  </parent>

  <artifactId>inventory.ui.html.app.war</artifactId>
  <packaging>war</packaging>

  <name>Inventory HTML UI Application</name>

  <build>
	<finalName>inventory-${project.version}</finalName>

    <!-- configure maven-resources-plugin to replace placeholders in resources -->
    <resources>
      <resource>
        <directory>${project.basedir}/src/main/resources</directory>
        <filtering>true</filtering>
      </resource>
    </resources>

    <plugins>
      <!-- configure maven-resources-plugin to use '\' as escape character  -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-resources-plugin</artifactId>
        <configuration>
          <escapeString>\</escapeString>
        </configuration>
      </plugin>
      <plugin>
        <artifactId>maven-antrun-plugin</artifactId>
        <executions>
          <execution>
            <phase>install</phase>
            <configuration>
              <target>
                <echo>Projet ${project.name}</echo>
                <copy file="target/inventory-${project.version}.war" tofile="${basedir}/dist/inventory-${project.version}.war"/>
                <copy file="target/inventory-${project.version}.war" tofile="${basedir}/../inventory/dist/current/inventory.war"/>
                <!-- 
                <copy todir="${basedir}/dist/conf">
                  <fileset dir="conf-default"/>
                </copy>
                <copy todir="${basedir}/dist">
                  <fileset dir="scripts"/>
                </copy>
                 -->
              </target>
            </configuration>
            <goals>
              <goal>run</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

  <dependencies>
    <dependency>
      <groupId>pers.mr.ft</groupId>
      <artifactId>inventory.ui.html</artifactId>
    </dependency>

    <!-- provided by container -->
    <dependency>
      <groupId>jakarta.servlet</groupId>
      <artifactId>jakarta.servlet-api</artifactId>
      <scope>provided</scope>
    </dependency>
  </dependencies>
</project>
