### Application
scout.application.name=FT Inventory Server
scout.application.version=${project.version}

### Service tunnel
scout.auth.publicKey=MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE9JDtXoiAsRESFSM/5D8DWTm3AnIuIdpiFWO+ieodqFAsfBhRGYO0qqhMg6g4zQHYWIb0YLrTvEO+Wqn7CSo9Tw==
