### Application
scout.application.name=Inventory
scout.application.version=${project.version}

### Service tunnel
scout.backendUrl=https://localhost:8443/pers.mr.ft.inventory.server
#scout.auth.privateKey=MD4CAQAwEAYHKoZIzj0CAQYFK4EEAAoEJzAlAgEBBCC7UD68qHbd3BZdd82F6yPNgBVvCXDzB6xugGaLw/3OUg==
scout.auth.privateKey=MEECAQAwEwYHKoZIzj0CAQYIKoZIzj0DAQcEJzAlAgEBBCCMsSIp24BRFzkihrUXQA+6j/msWlHLL3RnE3lyRx3BfA==
### Security
scout.auth.credentials=admin:Q5hBRXwi25yU57UdwZESrw==.cvvCvJLQmtdQSu2VI8Di4f0j/bmf6q3YFOfb3esdRLiXnNnWIl3wHjBI8QSu8K1TfO1lvADmb9aOc1GEEfXztA==;scott:xeCQwEtqP6sRfuvAYYUPHw==.6plBwhPiyYurpq8EysozTOrXe/FTw+pA3uyM0jnuPYz0zx16a4yDxVmhHik/YFiWGhTwMnhx4+bSk3rb5IOn+A==

### Storage location for FileSystemUserPreferencesStorageService
scout.client.userArea=${user.home}/ftdb-inventory

scout.ui.maxUserIdleTime=86400
