<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>pers.mr.ft</groupId>
    <artifactId>inventory</artifactId>
    <version>1.12.0-23.2</version>
    <relativePath>../inventory</relativePath>
  </parent>

  <artifactId>inventory.ui.html</artifactId>

  <name>Inventory HTML UI</name>

  <dependencies>
    <dependency>
      <groupId>org.eclipse.scout.rt</groupId>
      <artifactId>org.eclipse.scout.rt.ui.html</artifactId>
    </dependency>
    <dependency>
      <groupId>pers.mr.ft</groupId>
      <artifactId>inventory.client</artifactId>
    </dependency>
  </dependencies>
</project>
