<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>pers.mr.ft</groupId>
    <artifactId>inventory</artifactId>
    <version>1.12.0-25.1</version>
    <relativePath>../inventory</relativePath>
  </parent>

  <!-- Application leaf module with dependencies only relevant for development including config.properties/logback.xml -->
  <artifactId>inventory.ui.html.app.dev</artifactId>

  <dependencies>
    <dependency>
      <groupId>pers.mr.ft</groupId>
      <artifactId>inventory.ui.html.app</artifactId>
    </dependency>
  </dependencies>
</project>
