### Application
scout.application.name=Inventory
scout.application.version=development

### Environment
#scout.devMode=true
scout.auth.cookieSessionValidateSecure=false

### Service tunnel
scout.backendUrl=http://localhost:9080/inventory-server
scout.auth.privateKey=MD4CAQAwEAYHKoZIzj0CAQYFK4EEAAoEJzAlAgEBBCCjxNlaHSItl/fbKMCnbQJ/2jCAe8ziaGOUojDbcqvK8w==

### Security
scout.auth.credentials=ftdb:ftdb
scout.auth.credentialsPlaintext=true

### Storage location for FileSystemUserPreferencesStorageService
#scout.client.userArea=/share/Public/Tomcat/${user.name}/ft-inventory
scout.client.userArea=/share/Public/Tomcat/ft-inventory

scout.ui.maxUserIdleTime=86400
