### Application
scout.application.name=Inventory
scout.application.version=development

### Environment
scout.devMode=true
scout.auth.cookieSessionValidateSecure=false

### Service tunnel
scout.backendUrl=http://localhost:8081
scout.auth.privateKey=MEECAQAwEwYHKoZIzj0CAQYIKoZIzj0DAQcEJzAlAgEBBCDiG8OyIN6jSpw0XyfZ4V6yXTVfte/+OmhbRQ8m4QmsQw==

### Security
scout.auth.credentials=admin:admin;scott:tiger
scout.auth.credentialsPlaintext=true

### Storage location for FileSystemUserPreferencesStorageService
scout.client.userArea=${user.home}/ftdb-inventory

scout.ui.maxUserIdleTime=86400
#scout.ui.maxUserIdleTime=15
scout.ui.theme=ft
