### Application
scout.application.name=FT Inventory
scout.application.version=development

### Environment
scout.devMode=true

### Service tunnel
scout.backendUrl=http://localhost:8080
scout.auth.privateKey=MEECAQAwEwYHKoZIzj0CAQYIKoZIzj0DAQcEJzAlAgEBBCBLzHe/dYzC9evV5P5E7EoI9w//YgtzTKi6xxP8mYvIlw==

### Security
scout.auth.credentials=admin:admin;scott:tiger
scout.auth.credentialsPlaintext=true

### Storage location for FileSystemUserPreferencesStorageService
scout.client.userArea=${user.home}/pers.mr.ft-inventory.ui.html.dev
