### Application
scout.application.name=Inventory Server
scout.application.version=development

### Environment
scout.devMode=true

### Service tunnel
#scout.auth.publicKey=MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAENimj+a/zyllCDGZz7BWZL7HB6EjBVfFIchAPjO73yfBPKAbmZu5YRnKYC2ISa/8ZOqBb7TrDNsze3JoqxFfM/A==
scout.auth.publicKey=MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEVr4i/7seNF260+OBbAKK4wLl9wD85JF1YMkWPDGbR5oPlTQZyRMuUKWiWhnoxT2Zoe5JzrygA6qHmAEPhqgXFg==


inventory.database.jdbc.mappingName=jdbc:postgresql://qnap2:5432/ftdb-qualif
inventory.database.jdbc.username=ftdb
inventory.database.jdbc.password=ftdb

