### Application
scout.application.name=FT Inventory Server
scout.application.version=development

### Environment
scout.devMode=true

### Service tunnel
scout.auth.publicKey=MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEqCeuJ2he7EzeY2ofs/5vKIhT1DwID6VxCNQ5vW8mffMGI9tp0JwzdntCcB5rJjouXbI+amrVqVlGPAmXXjCe1w==
