### Application
scout.application.name=Inventory Server
scout.application.version=${project.version}

### Service tunnel
scout.auth.publicKey=MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE29mBJYVJ9wVXVnllU3AoS4tX6xHE1YQAK5RhlDzOrciAuXuqfT5PMNWYNePq6c3sKS61H0cmtKThW3BeuC4tEQ==
